[package]
name = "session-test"
version = "0.1.0"
authors = ["Søren"]

[dependencies]
iron = "*"
#session = { "path" = "../session" }
session = { git = "https://github.com/sorenhoyer/session", branch = "refactor/iron" }
